= Establishing the Archive pattern
:revdate: 2026-09-10
:status: Draft
:toc:

== Context

We need a standard way to write documents that are used as reference and provide context for future maintainers. This document establishes the pattern.

== What's an archive?

Archives are files inside a `archive/` folder. They are files that are relevant to the project where the folder is located, and provide valuable context for maintaners and AI agents working in the project. Besides being a text file, two properties must hold to any file inside an Archive:

1) They are carefully thought-out documents, that provide relevant context for future readers.

They are not throwaway files generated by LLMs during implementation, or quick notes written in a meeting. They are vetted by a stakeholder that can defend its existance inside the archive.

2) They are live documents tracked by a VCS.

The documents correctly describe the state in the particular commit they are. If a statement on the document goes stale, it must be updated to reflect the change. They must not maintain a changelog, since the VCs already provides that.

== How to write a document in the archive

If you read the above criteria and decided to write a document, the process to write is as follows:

1) Decide which folder inside the archive it must hold

Each project is free to implement its structure, scoping the documents as needed inside folders (also called [Drawers])

2) Calculate the ID

All document names must start with a monotonically increasing number, scoped by the folder it is on.

3) Define the category

After the ID, the name must contain the category divided by a dot. For example, for software specs, the category may be the piece of software impacted by the spec.

Categories can be defined by <id>.<category-name>.<ext>, which provides context on what the category entails

4) Define the name

Finally, the actual document name. At the end, the structure is `<id>.<category-name>.<doc-name>.<ext>`

== Defining drawers

Drawers are folders inside an Archive. They are optional, and provide some tree like structure. You can have drawers inside drawers (which kind of breaks the abstraction name down, but...).

Notably, you can provide context on what document a drawer should hold in a file inside the folder that does not require an ID, named with the same name as the folder. Such files are called *definition files*. For example, a folder called `customers` can have a file `customers/customers.<ext>`, explaining what types of documents should go inside.

Drawers can also define the structure of the documents that go inside. The structure must be defined in the definition file.
